"""add wren_models jsonb to chatbots

Revision ID: 0664d7410ba0
Revises: a1b2c3d4e5f6
Create Date: 2026-04-16 11:30:44.358672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0664d7410ba0'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE artifacts SET title = '' WHERE title IS NULL")
    op.alter_column('artifacts', 'title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.add_column('chatbot_csvs', sa.Column('is_success', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('chatbots', sa.Column('wren_models', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'wren_models')
    op.drop_column('chatbot_csvs', 'is_success')
    op.alter_column('artifacts', 'title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
