"""add alert_schedule table

Revision ID: 270fbd8a4f04
Revises: 534adbd1c9f3
Create Date: 2026-02-09 11:59:51.261123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270fbd8a4f04'
down_revision: Union[str, Sequence[str], None] = '534adbd1c9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_name', sa.String(), nullable=False),
    sa.Column('is_normal', sa.Boolean(), nullable=False),
    sa.Column('send_schedule', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('ads_str', sa.String(), nullable=False),
    sa.Column('send_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_schedule')
    # ### end Alembic commands ###
