"""add table_location and type to organizations

Revision ID: 29901f2f2ea9
Revises: 0fe1490cf49d
Create Date: 2026-01-21 10:53:59.365683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29901f2f2ea9'
down_revision: Union[str, Sequence[str], None] = '0fe1490cf49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('table_location', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'type')
    op.drop_column('organizations', 'table_location')
    # ### end Alembic commands ###
