"""logo

Revision ID: 351c5669a6d3
Revises: b5adb01c6145
Create Date: 2025-11-07 12:29:44.238424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351c5669a6d3'
down_revision: Union[str, Sequence[str], None] = 'b5adb01c6145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo', sa.String(), nullable=True))
    op.drop_column('organizations', 'logo_url')
    op.add_column('si', sa.Column('logo', sa.String(), nullable=True))
    op.drop_column('si', 'logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('si', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('si', 'logo')
    op.add_column('organizations', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'logo')
    # ### end Alembic commands ###
