"""update user_role_table pk

Revision ID: 3b73134b93e3
Revises: a231e97eec0b
Create Date: 2025-11-20 10:56:45.473741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b73134b93e3"
down_revision: Union[str, Sequence[str], None] = "a231e97eec0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('user_roles', 'role_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.drop_constraint(op.f('user_roles_user_id_role_id_scope_type_scope_id_key'), 'user_roles', type_='unique')
    # ### end Alembic commands ###
    #
    # 1. Drop old PK (user_id, role_id)
    #
    op.drop_constraint("user_roles_pkey", "user_roles", type_="primary")

    #
    # 2. Drop old unique constraint
    #
    op.drop_constraint(
        op.f("user_roles_user_id_role_id_scope_type_scope_id_key"),
        "user_roles",
        type_="unique",
    )

    #
    # 3. Create new PK (user_id, scope_type, scope_id)
    #
    op.create_primary_key(
        "user_roles_pkey", "user_roles", ["user_id", "scope_type", "scope_id"]
    )

    #
    # 4. Make role_id nullable (possible only after removing PK)
    #
    op.alter_column("user_roles", "role_id", existing_type=sa.INTEGER(), nullable=True)

    #
    # 5. Clean old data to satisfy new check constraint
    #    super, si → role_id must be NULL
    #
    op.execute(
        """
        UPDATE user_roles
        SET role_id = NULL
        WHERE scope_type IN ('super','si');
    """
    )

    #
    # 6. Add new check constraint for role_id logic
    #
    op.create_check_constraint(
        "ck_user_roles_scope_role_logic",
        "user_roles",
        "(scope_type = 'org' AND role_id IS NOT NULL AND role_id > 0) OR "
        "(scope_type IN ('super','si') AND role_id IS NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(
    #     op.f("user_roles_user_id_role_id_scope_type_scope_id_key"),
    #     "user_roles",
    #     ["user_id", "role_id", "scope_type", "scope_id"],
    #     postgresql_nulls_not_distinct=False,
    # )
    # op.alter_column("user_roles", "role_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
    # Remove the new check constraint
    #
    # 1. Remove new check constraint
    #
    op.drop_constraint("ck_user_roles_scope_role_logic", "user_roles", type_="check")

    #
    # 2. Drop new PK (user_id, scope_type, scope_id)
    #
    op.drop_constraint("user_roles_pkey", "user_roles", type_="primary")

    #
    # 3. Recreate old PK (user_id, role_id)
    #
    op.create_primary_key("user_roles_pkey", "user_roles", ["user_id", "role_id"])

    #
    # 4. role_id must NOT NULL (old schema)
    #
    op.alter_column("user_roles", "role_id", existing_type=sa.INTEGER(), nullable=False)

    #
    # 5. Restore old unique constraint
    #
    op.create_unique_constraint(
        op.f("user_roles_user_id_role_id_scope_type_scope_id_key"),
        "user_roles",
        ["user_id", "role_id", "scope_type", "scope_id"],
        postgresql_nulls_not_distinct=False,
    )
