"""rename

Revision ID: 6b3c9d50d205
Revises: 8ed51d33b10d
Create Date: 2025-11-11 17:32:22.320088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b3c9d50d205"
down_revision: Union[str, Sequence[str], None] = "8ed51d33b10d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_permissions",
        sa.Column("si_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["si_id"], ["si.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("si_id", "permission_id"),
    )
    op.create_table(
        "org_permissions",
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", "permission_id"),
    )
    op.drop_table("user_si")
    op.drop_table("user_org")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_org",
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("user_org_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("user_org_permission_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "permission_id", name=op.f("user_org_pkey")
        ),
    )
    op.create_table(
        "user_si",
        sa.Column("si_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("user_si_permission_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["si_id"], ["si.id"], name=op.f("user_si_si_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("si_id", "permission_id", name=op.f("user_si_pkey")),
    )
    op.drop_table("org_permissions")
    op.drop_table("si_permissions")
    # ### end Alembic commands ###
