"""remove chatbot org user

Revision ID: 6bbcb00d1a2c
Revises: 745505c88dc5
Create Date: 2026-03-17 10:59:13.103925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bbcb00d1a2c'
down_revision: Union[str, Sequence[str], None] = '745505c88dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_user_chatbot_chatbot_id'), table_name='org_user_chatbot')
    op.drop_index(op.f('ix_org_user_chatbot_org_user_last'), table_name='org_user_chatbot')
    op.drop_table('org_user_chatbot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_user_chatbot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chatbot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name=op.f('org_user_chatbot_chatbot_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('org_user_chatbot_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('org_user_chatbot_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('org_user_chatbot_pkey'))
    )
    op.create_index(op.f('ix_org_user_chatbot_org_user_last'), 'org_user_chatbot', ['org_id', 'user_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_org_user_chatbot_chatbot_id'), 'org_user_chatbot', ['chatbot_id'], unique=False)
    # ### end Alembic commands ###
