"""update schedule table

Revision ID: 745505c88dc5
Revises: 6ff942bc1bf3
Create Date: 2026-03-06 11:56:35.708843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745505c88dc5'
down_revision: Union[str, Sequence[str], None] = '6ff942bc1bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_schedule', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('alert_schedule', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('alert_schedule_user_id_fkey'), 'alert_schedule', type_='foreignkey')
    op.drop_column('alert_schedule', 'user_id')
    op.drop_column('alert_schedule', 'is_normal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_schedule', sa.Column('is_normal', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('alert_schedule', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('alert_schedule_user_id_fkey'), 'alert_schedule', 'users', ['user_id'], ['id'])
    op.drop_column('alert_schedule', 'is_recurring')
    op.drop_column('alert_schedule', 'email')
    # ### end Alembic commands ###
