"""update column

Revision ID: 780ec5238632
Revises: 9993c7d42a2c
Create Date: 2025-11-17 14:12:33.166917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "780ec5238632"
down_revision: Union[str, Sequence[str], None] = "9993c7d42a2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely."""

    # 1️⃣ Backfill nulls before constraint enforcement
    op.execute(
        """
        UPDATE organizations
        SET contract_start = NOW()
        WHERE contract_start IS NULL;
    """
    )
    op.execute(
        """
        UPDATE organizations
        SET contract_end = NOW()
        WHERE contract_end IS NULL;
    """
    )

    # 2️⃣ Enforce NOT NULL + add default for new inserts
    op.alter_column(
        "organizations",
        "contract_start",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "organizations",
        "contract_end",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text("now()"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organizations",
        "contract_end",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "organizations",
        "contract_start",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###
