"""add threads messages artifacts

Revision ID: 7890367d4ed6
Revises: 6bbcb00d1a2c
Create Date: 2026-03-17 16:06:01.598585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7890367d4ed6'
down_revision: Union[str, Sequence[str], None] = '6bbcb00d1a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_org_chatbot_last_msg', 'threads', ['org_id', 'chatbot_id', 'last_message_at'], unique=False)
    op.create_index('ix_threads_org_user_last_msg', 'threads', ['org_id', 'user_id', 'last_message_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'tool', name='messagerole'), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'markdown', 'json', 'tool_call', 'tool_result', 'image_ref', 'error', name='messagecontenttype'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('final', 'streaming', 'failed', 'cancelled', name='messagestatus'), nullable=False),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_thread_created_at', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_index('ix_messages_thread_seq', 'messages', ['thread_id', 'seq'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('chart', 'table', 'image', 'file', 'code', 'json_schema', name='artifacttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_message_id', 'artifacts', ['message_id'], unique=False)
    op.create_index('ix_artifacts_thread_created_at', 'artifacts', ['thread_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artifacts_thread_created_at', table_name='artifacts')
    op.drop_index('ix_artifacts_message_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_messages_thread_seq', table_name='messages')
    op.drop_index('ix_messages_thread_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_threads_org_user_last_msg', table_name='threads')
    op.drop_index('ix_threads_org_chatbot_last_msg', table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###
