"""add business table

Revision ID: 8ed51d33b10d
Revises: 351c5669a6d3
Create Date: 2025-11-11 17:29:46.975390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed51d33b10d'
down_revision: Union[str, Sequence[str], None] = '351c5669a6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_si',
    sa.Column('si_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['si_id'], ['si.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('si_id', 'permission_id')
    )
    op.create_table('org_business_modules',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('business_modules_id', sa.Integer(), nullable=False),
    sa.Column('enabled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_modules_id'], ['business_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'business_modules_id')
    )
    op.create_table('user_org',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_org')
    op.drop_table('org_business_modules')
    op.drop_table('user_si')
    op.drop_table('business_modules')
    # ### end Alembic commands ###
