"""update association

Revision ID: 9203ed042520
Revises: b1c020332779
Create Date: 2025-11-04 16:32:57.954721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9203ed042520'
down_revision: Union[str, Sequence[str], None] = 'b1c020332779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('isActive', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('user_roles_user_id_role_id_scope_type_scope_id_isActiveOrg_key'), 'user_roles', type_='unique')
    op.create_unique_constraint(None, 'user_roles', ['user_id', 'role_id', 'scope_type', 'scope_id', 'isActive'])
    op.drop_column('user_roles', 'isActiveOrg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('isActiveOrg', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.create_unique_constraint(op.f('user_roles_user_id_role_id_scope_type_scope_id_isActiveOrg_key'), 'user_roles', ['user_id', 'role_id', 'scope_type', 'scope_id', 'isActiveOrg'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_roles', 'isActive')
    # ### end Alembic commands ###
