"""add contract date

Revision ID: 9993c7d42a2c
Revises: 18e189b7a936
Create Date: 2025-11-11 23:58:51.871769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9993c7d42a2c'
down_revision: Union[str, Sequence[str], None] = '18e189b7a936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('contract_start', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('contract_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'contract_end')
    op.drop_column('organizations', 'contract_start')
    # ### end Alembic commands ###
