"""remove isActive

Revision ID: a231e97eec0b
Revises: 780ec5238632
Create Date: 2025-11-18 14:12:18.670407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a231e97eec0b'
down_revision: Union[str, Sequence[str], None] = '780ec5238632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_roles_user_id_role_id_scope_type_scope_id_isActive_key'), 'user_roles', type_='unique')
    op.create_unique_constraint(None, 'user_roles', ['user_id', 'role_id', 'scope_type', 'scope_id'])
    op.drop_column('user_roles', 'isActive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.create_unique_constraint(op.f('user_roles_user_id_role_id_scope_type_scope_id_isActive_key'), 'user_roles', ['user_id', 'role_id', 'scope_type', 'scope_id', 'isActive'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
