"""update association permission

Revision ID: b1c020332779
Revises: b80e54068cf6
Create Date: 2025-11-04 16:02:31.160114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1c020332779"
down_revision: Union[str, Sequence[str], None] = "b80e54068cf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("permissions", sa.Column("type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permissions", "type")
    # ### end Alembic commands ###
