"""add index

Revision ID: b5adb01c6145
Revises: c40bbadba8cb
Create Date: 2025-11-07 12:21:40.791649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5adb01c6145'
down_revision: Union[str, Sequence[str], None] = 'c40bbadba8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_roles_scope_type_scope_id', 'user_roles', ['scope_type', 'scope_id'], unique=False)
    op.create_index('idx_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_roles_user_id', table_name='user_roles')
    op.drop_index('idx_user_roles_scope_type_scope_id', table_name='user_roles')
    # ### end Alembic commands ###
