"""modified user relate tables

Revision ID: bd83a1283575
Revises: 04a994d76d57
Create Date: 2025-10-29 17:03:59.306000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd83a1283575'
down_revision: Union[str, Sequence[str], None] = '04a994d76d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user_roles', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('user_roles', sa.Column('scope_type', sa.Enum('system', 'si', 'org', name='scopetype'), nullable=False))
    op.add_column('user_roles', sa.Column('scope_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'scope_id')
    op.drop_column('user_roles', 'scope_type')
    op.drop_column('user_roles', 'role_id')
    op.drop_column('user_roles', 'user_id')
    # ### end Alembic commands ###
