"""add logo

Revision ID: c40bbadba8cb
Revises: 36ffb2330f00
Create Date: 2025-11-07 12:17:42.091153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40bbadba8cb'
down_revision: Union[str, Sequence[str], None] = '36ffb2330f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('si', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('si', 'logo_url')
    op.drop_column('organizations', 'logo_url')
    # ### end Alembic commands ###
