"""add report tables - report_tabs, report_groups, reports, user_report_tab_accesses

Revision ID: c96a41bded0d
Revises: 8cf6334b357d
Create Date: 2025-12-23 17:05:31.523510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96a41bded0d'
down_revision: Union[str, Sequence[str], None] = '8cf6334b357d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['report_tabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_report_tab_accesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['report_tabs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('looker_url', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['report_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_organizations_si_active'), table_name='organizations')
    op.drop_index(op.f('idx_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('idx_si_disabled'), table_name='si')
    op.drop_index(op.f('idx_user_roles_user_scope'), table_name='user_roles')
    op.drop_index(op.f('idx_user_roles_user_scope_composite'), table_name='user_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_roles_user_scope_composite'), 'user_roles', ['user_id', 'scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('idx_user_roles_user_scope'), 'user_roles', ['user_id', 'scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('idx_si_disabled'), 'si', ['disabled'], unique=False)
    op.create_index(op.f('idx_role_permissions_role'), 'role_permissions', ['role_id', 'permission_id'], unique=False)
    op.create_index(op.f('idx_organizations_si_active'), 'organizations', ['si_id', 'disabled'], unique=False)
    op.drop_table('reports')
    op.drop_table('user_report_tab_accesses')
    op.drop_table('report_groups')
    op.drop_table('report_tabs')
    # ### end Alembic commands ###
