"""add wren_ai_thread_id

Revision ID: cc58f4b95eee
Revises: 7890367d4ed6
Create Date: 2026-03-17 17:01:22.693883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc58f4b95eee'
down_revision: Union[str, Sequence[str], None] = '7890367d4ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('wren_thread_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'threads', ['wren_thread_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='unique')
    op.drop_column('threads', 'wren_thread_id')
    # ### end Alembic commands ###
