"""add key

Revision ID: f0ad3179786b
Revises: 3a5f97c53850
Create Date: 2025-12-02 15:04:58.426139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0ad3179786b"
down_revision: Union[str, Sequence[str], None] = "3a5f97c53850"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column nullable=True
    op.add_column("permissions", sa.Column("key", sa.String(), nullable=True))

    # 2. Backfill existing rows with a generated value
    #    Example: use the permission ID or name to form a unique key
    op.execute(
        """
        UPDATE permissions
        SET key = 'perm_' || id  -- or name, or some other unique column
    """
    )

    # 3. Add unique constraint
    op.create_unique_constraint("uq_permissions_key", "permissions", ["key"])

    # 4. Change column to NOT NULL
    op.alter_column("permissions", "key", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permissions", type_="unique")
    op.drop_column("permissions", "key")
    # ### end Alembic commands ###
